import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FakeDataService {
  private restaurants: any = [];
  constructor() {
    this.restaurants = this.getData();
  }

  getRestaurant(restaurantId: string) {
    return this.restaurants.find((r) => r.id == restaurantId)
  }

  getData(): any[] {
    return [
      // Store #01
      {
        id: 'ZE00003',
        name: 'Home Made Vegetarian Food',
        raddress: 'Petaling Jaya. Selangor',
        reviewsCount: 6,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s1/banner/VegetarianFood.jpg',
        avatarImage: 'assets/s1/banner/VegetarianFood.jpg',
        logo: 'assets/s1/icon/logo_transparent.png',
        icon: '',
        phoneNumber: '60163529480',
        deliveryFee: 0.00,
        image: 'assets/s1/icon/logo_transparent.png',
        categories: [
          {
            id: 1,
            title: "Main",
            total: 2,
          },
          {
            id: 2,
            title: "Snacks",
            total: 2,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Hara Bhara kabab",
            description: "Hara Bhara kabab 1pcs",
            price: 2.00,
            count: 0,
            image:
              "assets/s1/hara-bhara-kabab.jpg",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Buff Vada",
            description: "Buff Vada 1pcs",
            price: 2.00,
            count: 0,
            image:
              "assets/s1/buff-vada.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Aloo Vada",
            // description: "this is just example",
            price: 1.50,
            count: 0,
            image:
              "assets/s1/aloo-bonda.jpg",
          },
          {
            id: 4,
            categoryId: 2,
            name: "Veg Biryani",
            // description: "this is just example",
            price: 13.50,
            count: 0,
            image: "assets/s1/vegbiryani.jpg",
          },
          {
            id: 5,
            categoryId: 2,
            name: "Puran poli",
            description: "Puran poli 2pcs",
            price: 6.00,
            count: 0,
            image:
              "assets/s1/puran-poli.jpg",
          },
          {
            id: 6,
            categoryId: 4,
            name: "Dahi Vada",
            description: "Dahivada 1plate",
            price: 10.00,
            count: 0,
            image:
              "assets/s1/Dahivada.jpeg",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Sev tameta nu shaak",
            description: "Sev tameta nu shaak",
            price: 9.50,
            count: 0,
            image:
              "assets/s1/sev-tameta-nu-shaak-recipe-1.jpg",
          },
          {
            id: 8,
            categoryId: 4,
            name: "Cheese Corn Tikki",
            description: "Cheese Corn Tikki 2pcs",
            price: 6.00,
            count: 0,
            image: "assets/s1/CheeseCornTikki.jpg",
          },
          {
            id: 9,
            categoryId: 2,
            name: "Paneer Tikki",
            description: "Paneer Tikki 2pcs",
            price: 6.00,
            count: 0,
            image: "assets/s1/Paneer_Tikkis.jpg",
          },
          {
            id: 10,
            categoryId: 4,
            name: "Aloo Tikki",
            description: "Aloo Tikki 1pcs",
            price: 1.50,
            count: 0,
            image: "assets/s1/Aloo-Tikki.jpg",
          },
          {
            id: 11,
            categoryId: 2,
            name: "Cheese Spring Roll",
            description: "Cheese Spring Roll 1pcs",
            price: 2.00,
            count: 0,
            image: "assets/s1/Chinese-Spring-Roll.jpg",
          },
          {
            id: 12,
            categoryId: 4,
            name: "Khajoor Roll",
            description: "Khajoor Roll",
            price: 1.50,
            count: 0,
            image: "assets/s1/KhajoorRoll.jpg",
          },
          {
            id: 13,
            categoryId: 4,
            name: "Aloo sabji",
            description: "Aloo sabji",
            price: 5.00,
            count: 0,
            image: "assets/s1/1.jpeg",
          },
          {
            id: 14,
            categoryId: 4,
            name: "Methi thepla",
            description: "Methi thepla 1pcs.",
            price: 2.00,
            count: 0,
            image: "assets/s1/2.jpeg",
          },
          {
            id: 15,
            categoryId: 4,
            name: "Pav Bhaji",
            description: "Pav Bhaji 2pcs.",
            price: 8.00,
            count: 0,
            image: "assets/s1/3.jpeg",
          },
          {
            id: 16,
            categoryId: 4,
            name: "Bitroot Paratha",
            description: "Bitroot Paratha 1pcs.",
            price: 2.50,
            count: 0,
            image: "assets/s1/4.jpeg",
          },
          {
            id: 17,
            categoryId: 4,
            name: "Carrot halva",
            description: "Carrot halva",
            price: 5.00,
            count: 0,
            image: "assets/s1/5.jpeg",
          },
          {
            id: 18,
            categoryId: 4,
            name: "Beetroot Halwa",
            description: "Beetroot Halwa 500gm",
            price: 40.00,
            count: 0,
            image: "assets/s1/6.jpeg",
          },
          {
            id: 19,
            categoryId: 4,
            name: "Vada pav",
            description: "Vada pav 1pcs",
            price: 7.00,
            count: 0,
            image: "assets/s1/7.jpeg",
          },
          {
            id: 20,
            categoryId: 4,
            name: "Puri",
            description: "Puri 500gm.",
            price: 20.00,
            count: 0,
            image: "assets/s1/8.jpeg",
          },
          {
            id: 21,
            categoryId: 4,
            name: "dabeli",
            description: "dabeli 1pcs",
            price: 7.00,
            count: 0,
            image: "assets/s1/9.jpeg",
          },
          {
            id: 22,
            categoryId: 4,
            name: "Crispi Bhakhri",
            description: "Crispi Bhakhri 1pcs",
            price: 2.00,
            count: 0,
            image: "assets/s1/10.jpeg",
          },
          {
            id: 23,
            categoryId: 4,
            name: "Ragda Petis",
            description: "Ragda Petis 1pcs",
            price: 8.00,
            count: 0,
            image: "assets/s1/11.jpeg",
          },
          {
            id: 24,
            categoryId: 4,
            name: "Gulab jamun",
            description: "Gulab jamun 3ps",
            price: 5.00,
            count: 0,
            image: "assets/s1/12.jpeg",
          },
          {
            id: 25,
            categoryId: 4,
            name: "Carrot Paratha",
            description: "Carrot Paratha 1pcs",
            price: 2.00,
            count: 0,
            image: "assets/s1/13.jpeg",
          },
          {
            id: 26,
            categoryId: 4,
            name: "Carrot halva",
            description: "Carrot halva RM 5.",
            price: 5.00,
            count: 0,
            image: "assets/s1/14.jpeg",
          },
          {
            id: 27,
            categoryId: 4,
            name: "Poha Chevda",
            description: "Poha Chevda 500gm.",
            price: 30.00,
            count: 0,
            image: "assets/s1/16.jpeg",
          },
          {
            id: 28,
            categoryId: 4,
            name: "Methi Papad",
            description: "Methi Papad 1pcs.",
            price: 10.00,
            count: 0,
            image: "assets/s1/17.jpeg",
          },
          {
            id: 29,
            categoryId: 4,
            name: "Chili Pokoda",
            description: "Chili Pokoda 2 pcs.",
            price: 5.00,
            count: 0,
            image: "assets/s1/18.jpeg",
          },
        ],
      },
      // Store #02
      {
        id: 'ZE000017',
        name: 'Ang Hair Salon',
        raddress: 'Kuantan. Pahang',
        reviewsCount: 3,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s2/banner/Haircut.jpg',
        avatarImage: 'assets/s2/banner/Haircut.jpg',
        logo: 'assets/s2/icon/Capture-HairCutSaloon.PNG',
        icon: '',
        phoneNumber: '601116123179',
        deliveryFee: 0.0,
        image: 'assets/s2/icon/Capture-HairCutSaloon.PNG',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Man haircut 男士理发 Potongan rambut lelaki : RM15-30",
            description: "Make appointment for MAN haircut 预约男士理发 Buat temujanji untuk potongan rambut lelaki",
            price: 30.00,
            count: 0,
            image:
              "assets/s2/ManHaircut.jpg",

          },
          {
            id: 2,
            categoryId: 2,
            name: "Women haircut 女性理发 Potongan rambut wanita : RM20-50",
            description: "Make appointment for WOMEN haircut 预约女士理发 Buat janji untuk potongan rambut wanita",
            price: 50.00,
            count: 0,
            image:
              "assets/s2/WomenHaircut.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Children haircut 儿童理发 Potongan rambut kanak-kanak : RM5-10",
            description: "Make appointment for CHILDREN haircut 预约儿童理发 Buat janji untuk potongan rambut kanak-kanak",
            price: 10.00,
            count: 0,
            image:
              "assets/s2/ChildrenHairCut.jpg",
          },

        ],
      },
      // Store #07
      {
        id: 'ZE00008',
        name: 'NoBrandDrink',
        raddress: 'Plaza Damas, Sri Hartamas. Kuala Lumpur.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s7/banner/NoBrandDrink-BannerBackground.jpg',
        avatarImage: 'assets/s7/banner/NoBrandDrink-BannerBackground.jpg',
        logo: 'assets/s7/icon/NoBrandDrink-Logo3.png',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 3.00,
        image: 'assets/s7/icon/NoBrandDrink-Logo3.png',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Kopi Bungkus Kaw Kaw",
            description: "Coffee in the plastic bag. Local Kopitiam. ICE | PRE-ORDER *Only deliver every wednesday from 11am to 5pm, KL only *Last order on Tuesday 6pm",
            price: 3.60,
            count: 0,
            image:
              "assets/s7/NoBrandDrink-KopiBungkus-SKU1.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Kopi Box Kaw Kaw",
            description: "Coffee in the seal container. Local Kopitiam. ICE  | PRE-ORDER *Only deliver every wednesday from 11am to 5pm, KL only *Last order on Tuesday 6pm",
            price: 3.80,
            count: 0,
            image:
              "assets/s7/NoBrandDrink-KopiBungkus-SKU2.PNG",
          },
        ],
      },
      // Store #03
      {
        id: 'ZE00006',
        name: 'Ah Chong Durian',
        raddress: 'Damansara Perdana. Petaling Jaya. Selangor',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s3/banner/AhChongDurianMerchant-BackgroundImage.jpg',
        avatarImage: 'assets/s3/banner/AhChongDurianMerchant-BackgroundImage.jpg',
        logo: 'assets/s3/logo/Logo.jpeg',
        icon: '',
        phoneNumber: '60167749061',
        deliveryFee: 0.00,
        image: 'assets/s3/logo/Logo.jpeg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Kampung Durian",
            description: "Raub old durian tree. All in boxes, 500grams each. All fresh from Pahang. Characteristics: bitter with a little sweet, do not like to eat sweet people do not waste time to ask and order. 都是盒装，每一盒500g. 特征：苦带一点甜，完全不喜欢吃甜的人千万别浪费时间询问和下单了. Raub老树A等.",
            price: 20.00,
            count: 0,
            image:
              "assets/s3/AhChongDurian-SKU1.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "D2, D7, D24, D78, D123, Hor Loh ,D144 Durian",
            description: "Raub old durian tree. All in boxes, 500grams each. All fresh from Pahang. Characteristics: bitter with a little sweet, do not like to eat sweet people do not waste time to ask and order. 都是盒装，每一盒500g. 特征：苦带一点甜， 完全不喜欢吃甜的人千万别浪费时间询问和下单了. Raub老树A等.",
            price: 35.00,
            count: 0,
            image:
              "assets/s3/AhChongDurian-SKU2.PNG",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Musang King Durian",
            description: "Raub old durian tree. All in boxes, 500grams each. All fresh from Pahang. Characteristics: bitter with a little sweet, do not like to eat sweet people do not waste time to ask and order. 都是盒装，每一盒500g. 特征：苦带一点甜， 完全不喜欢吃甜的人千万别浪费时间询问和下单了. Raub老树A等.",
            price: 80.00,
            count: 0,
            image:
              "assets/s3/AhChongDurian-SKU3.PNG",
          },
        ],
      },
      // Store #04
      {
        id: 'ZE00002',
        name: 'KY Mobile Top Up',
        raddress: 'Kuala Terengganu. Terengganu',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s4/banner/bannerf.jpeg',
        avatarImage: 'assets/s4/banner/bannerf.jpeg',
        logo: 'assets/s4/StoreLogo/Capture-MobileTopUpLogo.png',
        icon: '',
        phoneNumber: '60189062227',
        deliveryFee: 0.00,
        image: 'assets/s4/StoreLogo/Capture-MobileTopUpLogo.png',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Celcom Top Up - 5",
            description: "Top up value for prepaid card -RM5 Celcom",
            price: 5.00,
            count: 0,
            image:
              "assets/s4/topup-celcom-RM5.jpg",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Celcom Top Up - 10",
            description: "Top up value for prepaid card - RM10 Celcom",
            price: 10.00,
            count: 0,
            image:
              "assets/s4/topup-celcom-RM10.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Celcom Top Up - 30",
            description: "Top up value for prepaid card - RM30 Celcom",
            price: 30.00,
            count: 0,
            image:
              "assets/s4/topup-celcom-RM30.jpg",
          },
          {
            id: 4,
            categoryId: 4,
            name: "DiGi Top Up - 5",
            description: "Top up value for prepaid card - RM5 Digi",
            price: 5.00,
            count: 0,
            image: "assets/s4/topup-digi-RM5.jpg",
          },
          {
            id: 5,
            categoryId: 1,
            name: "DiGi Top Up - 10",
            description: "Top up value for prepaid card - RM10 Digi",
            price: 10.00,
            count: 0,
            image: "assets/s4/topup-digi-RM10.jpg",
          },
          {
            id: 6,
            categoryId: 2,
            name: "DiGi Top Up - 30",
            description: "Top up value for prepaid card - RM30Digi",
            price: 30.00,
            count: 0,
            image: "assets/s4/topup-digi-RM30.jpg",
          },
          {
            id: 7,
            categoryId: 3,
            name: "HotLink Top Up - 5",
            description: "Top up value for prepaid card - RM5 HotLink",
            price: 5.00,
            count: 0,
            image: "assets/s4/topup-hotlink-RM5.jpg",
          },
          {
            id: 8,
            categoryId: 4,
            name: "HotLink Top Up - 10",
            description: "Top up value for prepaid card - RM10 HotLink",
            price: 10.00,
            count: 0,
            image: "assets/s4/topup-hotlink-RM10.jpg",
          },
          {
            id: 9,
            categoryId: 4,
            name: "HotLink Top Up - 30",
            description: "Top up value for prepaid card - RM30 HotLink",
            price: 30.00,
            count: 0,
            image: "assets/s4/topup-hotlink-RM30.jpg",
          },
          {
            id: 10,
            categoryId: 4,
            name: "RedOne Top Up - 5",
            description: "Top up value for prepaid card - RM5 RedOne",
            price: 5.00,
            count: 0,
            image: "assets/s4/topup-redone-RM5.jpg",
          },
          {
            id: 11,
            categoryId: 4,
            name: "RedOne Top Up - 10",
            description: "Top up value for prepaid card - RM10 RedOne",
            price: 10.00,
            count: 0,
            image: "assets/s4/topup-redone-RM10.jpg",
          },
          {
            id: 12,
            categoryId: 4,
            name: "RedOne Top Up - 30",
            description: "Top up value for prepaid card - RM30 RedOne",
            price: 30.00,
            count: 0,
            image: "assets/s4/topup-redone-RM30.jpg",
          },
        ]
      },
      // Store #05
      {
        id: 'ZE00007',
        name: 'Chantique Nasi Lemak',
        raddress: 'Langkawi. Kedah.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s5/banner/ChantiqueNasiLemakMerchant-BackgroundImage.jpg',
        avatarImage: 'assets/s5/banner/ChantiqueNasiLemakMerchant-BackgroundImage.jpg',
        logo: 'assets/s5/icon/ch.jpg',
        icon: '',
        phoneNumber: '60105581746',
        deliveryFee: 0.00,
        image: 'assets/s5/icon/ch.jpg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Nasi Lemak Bilis Telur",
            description: "Nasi lemak anchovies & egg",
            price: 6.00,
            count: 0,
            image:
              "assets/s5/chantiqueNasiLemak-SKU1.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Nasi Lemak Ayam Goreng",
            description: "Nasi lemak fried chicken",
            price: 8.50,
            count: 0,
            image:
              "assets/s5/chantiqueNasiLemak-SKU2.PNG",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Nasi Lemak Rendang Ayam",
            description: "Nasi lemak chicken rendang",
            price: 9.50,
            count: 0,
            image:
              "assets/s5/chantiqueNasiLemak-SKU3.PNG",
          },
          {
            id: 4,
            categoryId: 4,
            name: "Nasi Lemak Paru Balado",
            description: "Nasi lemak chilli beef lungs",
            price: 9.50,
            count: 0,
            image: "assets/s5/chantiqueNasiLemak-SKU4.PNG",
          },
          {
            id: 5,
            categoryId: 1,
            name: "Nasi Lemak Kacang Buncis",
            description: "Nasi lemak green beans",
            price: 7.50,
            count: 0,
            image: "assets/s5/chantiqueNasiLemak-SKU5.PNG",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Nasi Lemak Rendang Daging",
            description: "Nasi lemak beef rendang",
            price: 9.50,
            count: 0,
            image: "assets/s5/chantiqueNasiLemak-SKU6.PNG",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Nasi Lemak Sambal Sotong",
            description: "Nasi lemak spicy cuttlefish",
            price: 9.50,
            count: 0,
            image: "assets/s5/chantiqueNasiLemak-SKU7.PNG",
          },
          {
            id: 8,
            categoryId: 4,
            name: "Chef Special - Lontong",
            description: "Coconut soup with vegetable & rice cakes",
            price: 9.50,
            count: 0,
            image: "assets/s5/chantiqueNasiLemak-SKU8.PNG",
          },
        ]
      },
      // Store #06
      {
        id: 'ZE00011',
        name: 'Tanjung Sepat Fishball',
        raddress: 'Petaling Jaya. Selangor.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s6/banner/TanjungSepatMerchant-BackgroundImage.jpg',
        avatarImage: 'assets/s6/banner/TanjungSepatMerchant-BackgroundImage.jpg',
        logo: 'assets/s6/icon/TanjungSepatSeafoodLogo.jpg',
        icon: '',
        phoneNumber: '60122127909',
        deliveryFee: 0.00,
        image: 'assets/s6/icon/TanjungSepatSeafoodLogo.jpg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Fried Fish Ball",
            description: "Fried Fish Ball 15 pcs 炸丸15粒",
            price: 10.00,
            count: 0,
            image:
              "assets/s6/TanjunSepatFishBall-SKU1.jpg",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Fish Cake",
            description: "Fish Cake 6 pcs 鱼饼6片",
            price: 10.00,
            count: 0,
            image:
              "assets/s6/TanjunSepatFishBall-SKU2.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Spring Rolls",
            description: "Spring Rolls 9 pcs 春卷9条",
            price: 10.00,
            count: 0,
            image:
              "assets/s6/TanjunSepatFishBall-SKU3.jpg",
          },
          {
            id: 4,
            categoryId: 4,
            name: "Small Fried Fu Chuk",
            description: "Small Fried Fu Chuk 20 pcs 小豆支2O片",
            price: 9.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU4.jpg",
          },
          {
            id: 5,
            categoryId: 1,
            name: "Fried Bean curd",
            description: "Fried Bean curd 9 pcs 豆卜9片",
            price: 10.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU5.jpg",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Long Fu Chuk",
            description: "Long Fu Chuk 1 long pcs 长豆支1片",
            price: 9.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU6.jpg",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Spicy Vege Fish Cake",
            description: "Spicy Vege Fish Cake 7 pcs 辣菜饼7片",
            price: 15.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU7.jpg",
          },
          {
            id: 8,
            categoryId: 4,
            name: "Saury Fish Ball",
            description: "Saury Fish Ball Big 20 pcs 西刀大鱼丸20 粒",
            price: 16.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU8.jpg",
          },
          {
            id: 9,
            categoryId: 4,
            name: "Saury Fish Ball",
            description: " Saury Fish BallSmall 50 pcs 西刀小鱼丸50粒",
            price: 15.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU9.jpg",
          },
          {
            id: 10,
            categoryId: 4,
            name: "Fuk Chuk Roll",
            description: "Fuk Chuk Roll 6 pcs 豆支卷 6片 ",
            price: 9.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU10.jpg",
          },
          {
            id: 11,
            categoryId: 4,
            name: "Vege Fish Ball",
            description: "Vege Fish Ball 菜丸 ",
            price: 12.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU11.jpg",
          },
          {
            id: 12,
            categoryId: 4,
            name: "Fish Noodles",
            description: "Fish Noodles 鱼面 ",
            price: 12.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU12.jpg",
          },
          {
            id: 13,
            categoryId: 4,
            name: "Fu Zhou Fish Ball",
            description: "Fu Zhou Fish Ball 福州鱼丸 ",
            price: 12.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU13.jpg",
          },
          {
            id: 14,
            categoryId: 4,
            name: "Flower Fish Ball",
            description: "Flower Fish Ball 鱼花 ",
            price: 12.00,
            count: 0,
            image: "assets/s6/TanjunSepatFishBall-SKU14.jpg",
          },
        ]
      },
      // Store #08
      {
        id: 'ZE00027',
        name: 'Akshaya EC',
        raddress: 'Kuala Lumpur',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s8/47.jpeg',
        avatarImage: 'assets/s8/47.jpeg',
        logo: 'assets/s8/43.jpeg  ',
        icon: '',
        phoneNumber: '60167997215',
        deliveryFee: 8.00,
        image: 'assets/s8/43.jpeg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/1.jpeg",
          },
          {
            id: 2,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/2.jpeg",
          },
          {
            id: 3,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/3.jpeg",
          },
          {
            id: 4,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/4.jpeg",
          },
          {
            id: 5,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/5.jpeg",
          },
          {
            id: 6,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/6.jpeg",
          },
          {
            id: 7,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/7.jpeg",
          },
          {
            id: 8,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/8.jpeg",
          },
          {
            id: 9,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/9.jpeg",
          },
          {
            id: 10,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/10.jpeg",
          },
          {
            id: 11,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/11.jpeg",
          },
          {
            id: 12,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/12.jpeg",
          },
          {
            id: 13,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/13.jpeg",
          },
          {
            id: 14,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/14.jpeg",
          },
          {
            id: 15,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/15.jpeg",
          },
          {
            id: 16,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/16.jpeg",
          },
          {
            id: 17,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/17.jpeg",
          },
          {
            id: 18,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/18.jpeg",
          },
          {
            id: 19,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/19.jpeg",
          },
          {
            id: 20,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/20.jpeg",
          },
          {
            id: 21,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/21.jpeg",
          },
          {
            id: 22,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/22.jpeg",
          },
          {
            id: 23,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/23.jpeg",
          },
          {
            id: 24,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/24.jpeg",
          },
          {
            id: 25,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/25.jpeg",
          },
          {
            id: 26,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/26.jpeg",
          },
          {
            id: 27,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/27.jpeg",
          },
          {
            id: 28,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/28.jpeg",
          },
          {
            id: 29,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/29.jpeg",
          },
          {
            id: 30,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/30.jpeg",
          },
          {
            id: 31,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/31.jpeg",
          },
          {
            id: 32,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/32.jpeg",
          },
          {
            id: 33,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/33.jpeg",
          },
          {
            id: 34,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/34.jpeg",
          },
          {
            id: 35,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/35.jpeg",
          },
          {
            id: 36,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/36.jpeg",
          },
          {
            id: 37,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/37.jpeg",
          },
          {
            id: 38,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/38.jpeg",
          },
          {
            id: 39,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/39.jpeg",
          },
          {
            id: 40,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/40.jpeg",
          },
          {
            id: 41,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/41.jpeg",
          },
          {
            id: 42,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/42.jpeg",
          },
          {
            id: 43,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/43.jpeg",
          },
          {
            id: 44,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/44.jpeg",
          },
          {
            id: 45,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/45.jpeg",
          },
          {
            id: 46,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/46.jpeg",
          },
          {
            id: 47,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/47.jpeg",
          },
          {
            id: 48,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/48.jpeg",
          },
          {
            id: 49,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/49.jpeg",
          },
          {
            id: 50,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/50.jpeg",
          },
          {
            id: 51,
            categoryId: 1,
            name: "🌾Beautiful  linen  saree🌾",
            description: "4 weeks pre order",
            price: 112.00,
            count: 0,
            image: "assets/s8/51.jpeg",
          },


        ],
      },
      // Store #09
      {
        id: 'ZE00021',
        name: 'Ibrahim Albar Hainan Chicken Rice',
        raddress: 'Plaza Damas, Sri Hartamas. Kuala Lumpur.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s9/Logo/banner.PNG',
        avatarImage: 'assets/s9/Logo/banner.PNG',
        logo: 'assets/s9/Logo/logo.png',
        icon: '',
        phoneNumber: '60198165061',
        deliveryFee: 0.00,
        image: 'assets/s9/Logo/logo.png',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
          {
            id: 2,
            title: "Roasted",
            active: true,
          },
          {
            id: 3,
            title: "Steam ",
            active: true,
          },
          {
            id: 4,
            title: "Chicken Chop",
            active: true,
          },
          {
            id: 5,
            title: "Beijing Duck",
            active: true,
          },
          {
            id: 6,
            title: "Wantan Noodles ",
            active: true,
          },
          {
            id: 7,
            title: "Sayur-Sayuran ",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 2,
            name: "Roasted Whole Chicken",
            description: "",
            price: 58.00,
            count: 0,
            image: "assets/s9/ZE00021-RoastedChickenCategory.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Roasted Half Chicken",
            description: "",
            price: 30.00,
            count: 0,
            image: "assets/s9/ZE00021-RoastedChickenCategory.PNG",
          },
          {
            id: 3,
            categoryId: 2,
            name: "Roasted 1/4 Down Chicken",
            description: "",
            price: 18.00,
            count: 0,
            image: "assets/s9/ZE00021-RoastedChickenCategory.PNG",
          },
          {
            id: 4,
            categoryId: 2,
            name: "Roasted 1/4 Up Chicken",
            description: "",
            price: 15.00,
            count: 0,
            image: "assets/s9/ZE00021-RoastedChickenCategory.PNG",
          },
          {
            id: 5,
            categoryId: 2,
            name: "Roasted Chicken Rice-Drumstick",
            description: "",
            price: 9.00,
            count: 0,
            image: "assets/s9/ZE00021-RoastedChickenCategory.PNG",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Roasted Regular Chicken Rice",
            description: "",
            price: 8.00,
            count: 0,
            image: "assets/s9/ZE00021-RoastedChickenCategory.PNG",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Steam Whole Chicken",
            description: "",
            price: 65.00,
            count: 0,
            image: "assets/s9/ZE00021-SteamChickenCategory.PNG",
          },
          {
            id: 8,
            categoryId: 3,
            name: "Steam Half Chicken",
            description: "",
            price: 35.00,
            count: 0,
            image: "assets/s9/ZE00021-SteamChickenCategory.PNG",
          },
          {
            id: 9,
            categoryId: 3,
            name: "Steam 1/4 Down Chicken",
            description: "",
            price: 25.00,
            count: 0,
            image: "assets/s9/ZE00021-SteamChickenCategory.PNG",
          },
          {
            id: 10,
            categoryId: 3,
            name: "Steam 1/4 Up Chicken",
            description: "",
            price: 20.00,
            count: 0,
            image: "assets/s9/ZE00021-SteamChickenCategory.PNG",
          },
          {
            id: 11,
            categoryId: 3,
            name: "Steam Chicken Rice-Drumstick",
            description: "",
            price: 11.00,
            count: 0,
            image: "assets/s9/ZE00021-SteamChickenCategory.PNG",
          },
          {
            id: 12,
            categoryId: 3,
            name: "Steam Regular Chicken Rice",
            description: "",
            price: 10.00,
            count: 0,
            image: "assets/s9/ZE00021-SteamChickenCategory.PNG",
          },
          {
            id: 13,
            categoryId: 4,
            name: "Butter Chicken Chop",
            description: "",
            price: 15.00,
            count: 0,
            image: "assets/s9/ZE00021-ChickenChopCategory.PNG",
          },
          {
            id: 14,
            categoryId: 4,
            name: "Hainan Chicken Chop",
            description: "",
            price: 15.00,
            count: 0,
            image: "assets/s9/ZE00021-ChickenChopCategory.PNG",
          },
          {
            id: 15,
            categoryId: 4,
            name: "SOS Mango Chicken Chop",
            description: "",
            price: 15.00,
            count: 0,
            image: "assets/s9/ZE00021-ChickenChopCategory.PNG",
          },
          {
            id: 16,
            categoryId: 4,
            name: "Blackpepper Chicken Chop",
            description: "",
            price: 15.00,
            count: 0,
            image: "assets/s9/ZE00021-ChickenChopCategory.PNG",
          },
          {
            id: 17,
            categoryId: 4,
            name: "Salted Egg Chicken Chop",
            description: "",
            price: 18.00,
            count: 0,
            image: "assets/s9/ZE00021-ChickenChopCategory.PNG",
          },
          {
            id: 18,
            categoryId: 5,
            name: "Whole Duck",
            description: "",
            price: 65.00,
            count: 0,
            image: "assets/s9/ZE00021-BeijingDuckCategory.PNG",
          },
          {
            id: 19,
            categoryId: 5,
            name: "Half Duck",
            description: "",
            price: 35.00,
            count: 0,
            image: "assets/s9/ZE00021-BeijingDuckCategory.PNG",
          },
          {
            id: 20,
            categoryId: 5,
            name: "1/4 Down Duck",
            description: "",
            price: 25.00,
            count: 0,
            image: "assets/s9/ZE00021-BeijingDuckCategory.PNG",
          },
          {
            id: 21,
            categoryId: 5,
            name: "1/4 Up Duck",
            description: "",
            price: 20.00,
            count: 0,
            image: "assets/s9/ZE00021-BeijingDuckCategory.PNG",
          },
          {
            id: 22,
            categoryId: 5,
            name: "Duck Rice Drumstick",
            description: "",
            price: 11.00,
            count: 0,
            image: "assets/s9/ZE00021-BeijingDuckCategory.PNG",
          },
          {
            id: 23,
            categoryId: 5,
            name: "Regular Duck Rice",
            description: "",
            price: 10.00,
            count: 0,
            image: "assets/s9/ZE00021-BeijingDuckCategory.PNG",
          },
          {
            id: 24,
            categoryId: 6,
            name: "Roasted with Dumpling",
            description: "RM8.00/RM9.00",
            price: 9.00,
            count: 0,
            image: "assets/s9/ZE00021-WantanNoodleCategory.PNG",
          },
          {
            id: 25,
            categoryId: 6,
            name: "Steamed with Dumpling",
            description: "RM10.00/RM11.00",
            price: 11.00,
            count: 0,
            image: "assets/s9/ZE00021-WantanNoodleCategory.PNG",
          },
          {
            id: 26,
            categoryId: 6,
            name: "Beijing Duck with Dumpling",
            description: "RM10.00/RM11.00",
            price: 11.00,
            count: 0,
            image: "assets/s9/ZE00021-WantanNoodleCategory.PNG",
          },
          {
            id: 27,
            categoryId: 6,
            name: "BBQ Wantan Noodle",
            description: "",
            price: 9.00,
            count: 0,
            image: "assets/s9/ZE00021-WantanNoodleCategory.PNG",
          },
          {
            id: 28,
            categoryId: 6,
            name: "Beef Noodle",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/s9/ZE00021-WantanNoodleCategory.PNG",
          },
          {
            id: 29,
            categoryId: 7,
            name: "Bean Sprout",
            description: "",
            price: 6.00,
            count: 0,
            image: "assets/s9/ZE00021-SayurSayuranCategory.PNG",
          },
          {
            id: 30,
            categoryId: 7,
            name: "Pak Choi",
            description: "",
            price: 6.00,
            count: 0,
            image: "assets/s9/ZE00021-SayurSayuranCategory.PNG",
          },
          {
            id: 31,
            categoryId: 7,
            name: "Yow Mak",
            description: "",
            price: 6.00,
            count: 0,
            image: "assets/s9/ZE00021-SayurSayuranCategory.PNG",
          },
        ],
      },
      // Store #10
      {
        id: 'ZE00014',
        name: 'Syrian Kitchen',
        raddress: 'Damansara Perdana. Petaling Jaya. Selangor.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s10/Logo/banner.jpg',
        avatarImage: 'assets/s10/Logo/banner.jpg',
        logo: 'assets/s10/Logo/logo.PNG',
        icon: '',
        phoneNumber: '601160939104',
        deliveryFee: 0.00,
        image: 'assets/s10//Logo/logo.PNG',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 2,
            name: "Chicken Kebab ",
            description: "Chicken Kebab 5 pcs with bread",
            price: 20.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-ChickenKebab-SKU1.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Kofta Lamb",
            description: "Kofta Lamb 5 pcs with bread",
            price: 20.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-LambKebab-SKU2.PNG",
          },
          {
            id: 3,
            categoryId: 2,
            name: "Falafel Meals",
            description: "Meals 7psc with bread, serve veggies and saucee",
            price: 15.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-FalafelMeal-SKU3.PNG",
          },
          {
            id: 4,
            categoryId: 2,
            name: "Falafel Wrap",
            description: "Wrap with bread.",
            price: 9.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-FalafelWrap-SKU4.PNG",
          },
          {
            id: 5,
            categoryId: 2,
            name: "Tabula Salad",
            description: "",
            price: 13.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-TabulaSalad-SKU5.PNG",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Hummus 200g",
            description: "200g comes with arabic bread",
            price: 15.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-Hummus-SKU6and7.PNG",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Hummus 400g",
            description: "400g comes with arabic bread",
            price: 25.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-Hummus-SKU6and7.PNG",
          },
          {
            id: 8,
            categoryId: 3,
            name: "Hummus with lamb",
            description: "comes with arabic bread",
            price: 20.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-HummusWithLamb-SKU8.PNG",
          },
          {
            id: 9,
            categoryId: 3,
            name: "Shish Tweak",
            description: "Shish tawok, grilled chicken breast cubes",
            price: 25.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-ShishTweak-SKU9.PNG",
          },
          {
            id: 10,
            categoryId: 3,
            name: "Bazilla Chicken",
            description: "Basmati rice peas, rice with peas and carrots, filled with nuts, with pieces of chicken",
            price: 25.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-BazillaChicken-SKU10.PNG",
          },
          {
            id: 11,
            categoryId: 3,
            name: "Bazilla Lamb",
            description: "Basmati rice peas, rice with peas and carrots, filled with nuts, with pieces of lamb",
            price: 25.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-BazillaLamb-SKU11.PNG",
          },
          {
            id: 12,
            categoryId: 3,
            name: "Fish with Rice",
            description: "Sayadia (Fried Fish with rice come with sauce chilli)",
            price: 35.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-SayadiaFriedFishWithRice-SKU12.PNG",
          },
          {
            id: 13,
            categoryId: 4,
            name: "Fish with Fries",
            description: "Sayadia (Fried Fish with fries)",
            price: 30.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-SayadiaFriedFishWithFries-SKU13.PNG",
          },
          {
            id: 14,
            categoryId: 4,
            name: "Shawarma Lamb",
            description: "Lamb shawarma with veggies, fries, bread and garlic sauce",
            price: 30.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-ShawarmaLamb-SKU14.PNG",
          },
          {
            id: 15,
            categoryId: 4,
            name: "Butter milk chicken",
            description: "Fried Chicken with Buttermilk sauce (Boneless)",
            price: 50.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-ButterMilkChicken-SKU15.PNG",
          },
          {
            id: 16,
            categoryId: 4,
            name: "Dessert Tamari",
            description: "Tamari 1pcs",
            price: 5.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-TamariDessert-SKU16.PNG",
          },
          {
            id: 17,
            categoryId: 4,
            name: "Basbousa Cake",
            description: "Basbousa coconut cake 1pcs RM2 (min order 5pcs)",
            price: 10.00,
            count: 0,
            image: "assets/s10/SyrianKitchen-BasbousaCake-SKU17.PNG",
          },
        ],
      },
      // Store #11
      {
        id: 'ZE00020',
        name: 'Thai Sauce Store',
        raddress: 'Damansara Perdana. Petaling Jaya. Selangor.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s11/Logo/ThaiSauce-Background.webp',
        avatarImage: 'assets/s11/Logo/ThaiSauce-Background.webp',
        logo: 'assets/s11/Logo/ThaiSauceLogo.PNG',
        icon: '',
        phoneNumber: '60124858670',
        deliveryFee: 0.00,
        image: 'assets/s11//Logo/ThaiSauceLogo.PNG',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 2,
            name: "Home made Thai Sauce ",
            description: "Home made Thai sauce with special ingredients like lemon grass, shallot, kaffir lime etc. ready to eat sauce, it can be a dipping sauce or you can eat with seafood, meat, chicken, egg and any of your favourite food.",
            price: 15.00,
            count: 0,
            image: "assets/s11/ThaiSauce-SKU1.jpeg",
          },
        ],
      },
      // Store #12
      {
        id: 'ZE00036',
        name: 'Butcher Carey',
        raddress: 'A-0-10 Plaza Damas 3. Sri Hatamas. Kuala Lumpur.',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/S12/Logo/Carey-ZE00036-BackgroundImage.PNG',
        avatarImage: 'assets/S12/Logo/Carey-ZE00036-BackgroundImage.PNG',
        logo: 'assets/S12/Logo/Carey-Logo.PNG',
        icon: '',
        phoneNumber: '60193380811',
        deliveryFee: 0.00,
        image: 'assets/S12/Logo/Carey-Logo.PNG',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
          {
            id: 2,
            title: "USA STEAK",
            active: true,
          },
          {
            id: 3,
            title: "BRITISH STEAK",
            active: true,
          },
          {
            id: 4,
            title: "AUTRALIAN STEAK",
            active: true,
          },
          {
            id: 5,
            title: "JAPAN STEAK",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Starters - Beef Cups  ",
            description: "Tenderloin strips on lettuce with sesame infused balsamic and chili",
            price: 25.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 2,
            categoryId: 1,
            name: "Greens - Corn Salad ",
            description: "Lettuce, cron, red onion and tomatoes with vinaigrette dressing",
            price: 16.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 3,
            categoryId: 1,
            name: "Beef Salad",
            description: "Thinly sliced beef on a bed of salad leaves, red onion and tomatoes with sesame dressing",
            price: 26.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 4,
            categoryId: 1,
            name: "Avocado Salad",
            description: "Lettuce, avocado, nuts and tomatoes with citrus dressing",
            price: 23.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 5,
            categoryId: 1,
            name: "Pasta (Spaghetti) AGLIO OLIO",
            description: "Option of spicy, less spicy or non-spicy",
            price: 15.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 6,
            categoryId: 1,
            name: "Pasta (Spaghetti) Cheezy Indulgence",
            description: "",
            price: 21.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 7,
            categoryId: 1,
            name: "Pasta Option - ADD ONS Beef Strips ",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 8,
            categoryId: 1,
            name: "Pasta Option - ADD ONS Lamp Chop",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 9,
            categoryId: 1,
            name: "LAMB CHOP ",
            description: "Set of 3 pieces",
            price: 36.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 10,
            categoryId: 1,
            name: "SIDES - Fries",
            description: "",
            price: 9.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 11,
            categoryId: 1,
            name: "SIDES - Sweet Potato Fries",
            description: "",
            price: 14.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 12,
            categoryId: 1,
            name: "SIDES - Onion Rings",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 13,
            categoryId: 1,
            name: "SIDES - Corn on the COB",
            description: "",
            price: 7.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 14,
            categoryId: 1,
            name: "SIDES - SAUTE Mushrooms",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 15,
            categoryId: 1,
            name: "SIDES - SAUTE Broccolis",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 16,
            categoryId: 1,
            name: "SIDES - SAUTE Asparagus",
            description: "",
            price: 15.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 17,
            categoryId: 1,
            name: "SIDES - MASHED Potatoes",
            description: "",
            price: 12.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 18,
            categoryId: 1,
            name: "SIDES - Garlic Bread",
            description: "",
            price: 8.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 19,
            categoryId: 1,
            name: "SIDES - Side Salad",
            description: "",
            price: 5.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AllSteak.PNG",
          },
          {
            id: 20,
            categoryId: 2,
            name: "USA Platinum Prime Aungus RibEye 300g",
            description: "Grain Fed Black Aungus RibeEye 300g",
            price: 150.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-USASteak-SKU20to25.PNG",
          },
          {
            id: 21,
            categoryId: 2,
            name: "USA Platinum Prime Aungus RibEye 400g",
            description: "Grain Fed Black Aungus RibeEye 400g",
            price: 200.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-USASteak-SKU20to25.PNG",
          },
          {
            id: 22,
            categoryId: 2,
            name: "USA Platinum Prime Aungus RibEye 500g",
            description: "Grain Fed Black Aungus RibeEye 500g",
            price: 250.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-USASteak-SKU20to25.PNG",
          },
          {
            id: 23,
            categoryId: 2,
            name: "USA Platinum Prime Murray Grey RibEye 300g",
            description: "Murray Grey RibeEye 300g",
            price: 120.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-USASteak-SKU20to25.PNG",
          },
          {
            id: 24,
            categoryId: 2,
            name: "USA Platinum Prime Murray Grey RibEye 400g",
            description: "Murray Grey RibeEye 400g",
            price: 160.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-USASteak-SKU20to25.PNG",
          },
          {
            id: 25,
            categoryId: 2,
            name: "USA Platinum Prime Murray Grey RibEye 500g",
            description: "Murray Grey RibeEye 500g",
            price: 200.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-USASteak-SKU20to25.PNG",
          },
          {
            id: 26,
            categoryId: 3,
            name: "British Pure Bred Hereford Tenderlion 200g",
            description: "",
            price: 80.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 27,
            categoryId: 3,
            name: "British Pure Bred Hereford Tenderlion 300g",
            description: "",
            price: 110.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 28,
            categoryId: 3,
            name: "British Pure Bred Hereford Tenderlion 400g",
            description: "",
            price: 150.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 29,
            categoryId: 3,
            name: "British Pure Bred Hereford Tenderlion 500g",
            description: "",
            price: 170.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 30,
            categoryId: 3,
            name: "British Pure Bred Hereford Ribeye 200g",
            description: "",
            price: 60.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 31,
            categoryId: 3,
            name: "British Pure Bred Hereford Ribeye 300g",
            description: "",
            price: 80.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 32,
            categoryId: 3,
            name: "British Pure Bred Hereford Ribeye 400g",
            description: "",
            price: 100.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 33,
            categoryId: 3,
            name: "British Pure Bred Hereford Ribeye 500g",
            description: "",
            price: 120.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 34,
            categoryId: 3,
            name: "British Pure Bred Hereford Sirloin 200g",
            description: "",
            price: 60.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 35,
            categoryId: 3,
            name: "British Pure Bred Hereford Sirloin 300g",
            description: "",
            price: 80.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 36,
            categoryId: 3,
            name: "British Pure Bred Hereford Sirloin 400g",
            description: "",
            price: 100.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 37,
            categoryId: 3,
            name: "British Pure Bred Hereford Sirloin 500g",
            description: "",
            price: 120.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU26to29.PNG",
          },
          {
            id: 38,
            categoryId: 4,
            name: "Australia WAGYU PICHANHA MB9 300g",
            description: "",
            price: 180.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 39,
            categoryId: 4,
            name: "Australia WAGYU PICHANHA MB9 400g",
            description: "",
            price: 240.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 40,
            categoryId: 4,
            name: "Australia WAGYU PICHANHA MB9 500g",
            description: "",
            price: 300.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 41,
            categoryId: 4,
            name: "Australia WAGYU RIBEYE MB9 200g",
            description: "",
            price: 152.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 42,
            categoryId: 4,
            name: "Australia WAGYU RIBEYE MB9 300g",
            description: "",
            price: 228.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 43,
            categoryId: 4,
            name: "Australia WAGYU RIBEYE MB9 400g",
            description: "",
            price: 304.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 44,
            categoryId: 4,
            name: "Australia WAGYU RIBEYE MB9 500g",
            description: "",
            price: 380.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 45,
            categoryId: 4,
            name: "Austriali Angus Tenderloin 200g",
            description: "Pure Bred Tenderloin 200g",
            price: 90.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 46,
            categoryId: 4,
            name: "Austriali Angus Tenderloin 300g",
            description: "Pure Bred Tenderloin 300g",
            price: 120.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 47,
            categoryId: 4,
            name: "Austriali Angus Tenderloin 400g",
            description: "Pure Bred Tenderloin 400g",
            price: 170.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 48,
            categoryId: 4,
            name: "Austriali Angus Tenderloin 500g",
            description: "Pure Bred Tenderloin 500g ",
            price: 190.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 49,
            categoryId: 4,
            name: "Austriali Angus RibEye 200g",
            description: "Pure Bred RibeEye 200g",
            price: 66.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 50,
            categoryId: 4,
            name: "Austriali Angus RibEye 300g",
            description: "Pure Bred RibeEye 300g",
            price: 95.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 51,
            categoryId: 4,
            name: "Austriali Angus RibEye 400g",
            description: "Pure Bred RibeEye 400g",
            price: 126.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 52,
            categoryId: 4,
            name: "Austriali Angus RibEye 500g",
            description: "Pure Bred RibeEye 500g",
            price: 152.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 53,
            categoryId: 4,
            name: "Austriali Angus SIRLIOIN 200g",
            description: "Pure Bred SIRLIOIN 200g",
            price: 66.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 54,
            categoryId: 4,
            name: "Austriali Angus SIRLIOIN 300g",
            description: "Pure Bred SIRLIOIN 300g",
            price: 80.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 55,
            categoryId: 4,
            name: "Austriali Angus SIRLIOIN 400g",
            description: "Pure Bred SIRLIOIN 400g",
            price: 100.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 56,
            categoryId: 4,
            name: "Austriali Angus SIRLIOIN 500g",
            description: "Pure Bred SIRLIOIN 500g ",
            price: 120.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-AustraliaSteak.PNG",
          },
          {
            id: 57,
            categoryId: 5,
            name: "Japan A5 Miyazaki Picanha 300g",
            description: "",
            price: 330.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 58,
            categoryId: 5,
            name: "Japan A5 Miyazaki Picanha 400g",
            description: "",
            price: 440.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 59,
            categoryId: 5,
            name: "Japan A5 Miyazaki Picanha 500g",
            description: "",
            price: 550.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 60,
            categoryId: 5,
            name: "Japan A5 Miyazaki Rump 300g",
            description: "",
            price: 330.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 61,
            categoryId: 5,
            name: "Japan A5 Miyazaki Rump 400g",
            description: "",
            price: 440.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 62,
            categoryId: 5,
            name: "Japan A5 Miyazaki Rump 500g",
            description: "",
            price: 550.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 63,
            categoryId: 5,
            name: "Japan A5 Miyazaki Ribeye 200g",
            description: "",
            price: 320.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 64,
            categoryId: 5,
            name: "Japan A5 Miyazaki Ribeye 300g",
            description: "",
            price: 480.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 65,
            categoryId: 5,
            name: "Japan A5 Miyazaki Ribeye 400g ",
            description: "",
            price: 640.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 66,
            categoryId: 5,
            name: "Japan A5 Miyazaki Ribeye 500g",
            description: "",
            price: 800.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 67,
            categoryId: 5,
            name: "Japan A5 Omi Gyu Ribeye 200g",
            description: "",
            price: 390.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 68,
            categoryId: 5,
            name: "Japan A5 Omi Gyu Ribeye 300g",
            description: "",
            price: 585.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 69,
            categoryId: 5,
            name: "Japan A5 Omi Gyu Ribeye 400g",
            description: "",
            price: 780.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
          {
            id: 70,
            categoryId: 5,
            name: "Japan A5 Omi Gyu Ribeye 500",
            description: "",
            price: 975.00,
            count: 0,
            image: "assets/S12/Carey-ZE00036-BritishSteak-SKU30to33.PNG",
          },
        ],
      },

    ];
  }
}
