import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FakeDataService {
  private restaurants: any = [];
  constructor() {
    this.restaurants = this.getData();
   }

  getRestaurant(restaurantId: string) {
    return this.restaurants.find((r) =>  r.id == restaurantId)
  }

  getData(): any[] {
    return [
      // Store #01
      {
        id: 1,
        name: 'Home Made Indian Food',
        reviewsCount: 6,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s1/banner/VegetarianFood.jpg',
        avatarImage: 'assets/s1/banner/VegetarianFood.jpg',
        logo: 'assets/s1/icon/HomeMade.png',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 0.00,
        image: 'assets/s1/icon/HomeMade.png',
        categories: [
          {
            id: 1,
            title: "Main",
            total: 2,
          },
          {
            id: 2,
            title: "Snacks",
            total: 2,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Hara Bhara kabab",
            description: "Hara Bhara kabab 1pcs",
            price:2.00,
            count: 0,
            image:
              "assets/s1/hara-bhara-kabab.jpg",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Buff Vada",
            description: "Buff Vada 1pcs",
            price: 2.00,
            count: 0,
            image:
              "assets/s1/buff-vada.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Aloo Vada",
            description: "this is just example",
            price: 1.50,
            count: 0,
            image:
              "assets/s1/aloo-bonda.jpg",
          },
          {
            id: 4,
            categoryId: 2,
            name: "Veg Biryani",
            description: "this is just example",
            price: 13.50,
            count: 0,
            image: "assets/s1/vegbiryani.jpg",
          },
          {
            id: 5,
            categoryId: 2,
            name: "Puran poli",
            description: "Puran poli 2pcs",
            price: 6.00,
            count: 0,
            image:
              "assets/s1/puran-poli.jpg",
          },
          {
            id: 6,
            categoryId: 4,
            name: "Dahi Vada",
            description: "Dahivada 1plate",
            price: 10.00,
            count: 0,
            image:
              "assets/s1/Dahivada.jpeg",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Sev tameta nu shaak",
            description: "this is just example",
            price: 9.50,
            count: 0,
            image:
              "assets/s1/sev-tameta-nu-shaak-recipe-1.jpg",
          },
          {
            id: 8,
            categoryId: 4,
            name: "Cheese Corn Tikki",
            description: "Cheese Corn Tikki 2pcs",
            price: 6.00,
            count: 0,
            image: "assets/s1/CheeseCornTikki.jpg",
          },
          {
            id: 9,
            categoryId: 2,
            name: "Paneer Tikki",
            description: "Paneer Tikki 2pcs",
            price: 6.00,
            count: 0,
            image: "assets/s1/Paneer_Tikkis.jpg",
          },
          {
            id: 10,
            categoryId: 4,
            name: "Aloo Tikki",
            description: "Aloo Tikki 1pcs",
            price: 1.50,
            count: 0,
            image: "assets/s1/Aloo-Tikki.jpg",
          },
          {
            id: 11,
            categoryId: 2,
            name: "Cheese Spring Roll",
            description: "Cheese Spring Roll 1pcs",
            price: 2.00,
            count: 0,
            image: "assets/s1/Chinese-Spring-Roll.jpg",
          },
          {
            id: 12,
            categoryId: 4,
            name: "Khajoor Roll",
            description: "Khajoor Roll",
            price: 1.50,
            count: 0,
            image: "assets/s1/KhajoorRoll.jpg",
          },
          {
            id: 13,
            categoryId: 4,
            name: "Aloo sabji",
            description: "Aloo sabji",
            price: 5.00,
            count: 0,
            image: "assets/s1/1.jpeg",
          },
          {
            id: 14,
            categoryId: 4,
            name: "Methi thepla",
            description: "Methi thepla 1pcs.",
            price: 2.00,
            count: 0,
            image: "assets/s1/2.jpeg",
          },
          {
            id: 15,
            categoryId: 4,
            name: "Pav Bhaji",
            description: "Pav Bhaji 2pcs.",
            price: 8.00,
            count: 0,
            image: "assets/s1/3.jpeg",
          },
          {
            id: 16,
            categoryId: 4,
            name: "Bitroot Paratha",
            description: "Bitroot Paratha 1pcs.",
            price: 2.50,
            count: 0,
            image: "assets/s1/4.jpeg",
          },
          {
            id: 17,
            categoryId: 4,
            name: "Carrot halva",
            description: "Carrot halva",
            price: 5.00,
            count: 0,
            image: "assets/s1/5.jpeg",
          },
          {
            id: 18,
            categoryId: 4,
            name: "Beetroot Halwa",
            description: "Beetroot Halwa 500gm",
            price: 40.00,
            count: 0,
            image: "assets/s1/6.jpeg",
          },
          {
            id: 19,
            categoryId: 4,
            name: "Vada pav",
            description: "Vada pav 1pcs",
            price: 7.00,
            count: 0,
            image: "assets/s1/7.jpeg",
          },
          {
            id: 20,
            categoryId: 4,
            name: "Puri",
            description: "Puri 500gm.",
            price: 20.00,
            count: 0,
            image: "assets/s1/8.jpeg",
          },
          {
            id: 21,
            categoryId: 4,
            name: "dabeli",
            description: "dabeli 1pcs",
            price: 7.00,
            count: 0,
            image: "assets/s1/9.jpeg",
          },
          {
            id: 22,
            categoryId: 4,
            name: "Crispi Bhakhri",
            description: "Crispi Bhakhri 1pcs",
            price: 2.00,
            count: 0,
            image: "assets/s1/10.jpeg",
          },
          {
            id: 23,
            categoryId: 4,
            name: "Ragda Petis",
            description: "Ragda Petis 1pcs",
            price: 8.00,
            count: 0,
            image: "assets/s1/11.jpeg",
          },
          {
            id: 24,
            categoryId: 4,
            name: "Gulab jamun",
            description: "Gulab jamun 3ps",
            price: 5.00,
            count: 0,
            image: "assets/s1/12.jpeg",
          },
          {
            id: 25,
            categoryId: 4,
            name: "Carrot Paratha",
            description: "Carrot Paratha 1pcs",
            price: 2.00,
            count: 0,
            image: "assets/s1/13.jpeg",
          },
          {
            id: 26,
            categoryId: 4,
            name: "Carrot halva",
            description: "Carrot halva RM 5.",
            price: 5.00,
            count: 0,
            image: "assets/s1/14.jpeg",
          },
          {
            id: 27,
            categoryId: 4,
            name: "Poha Chevda",
            description: "Poha Chevda 500gm.",
            price: 30.00,
            count: 0,
            image: "assets/s1/16.jpeg",
          },
          {
            id: 28,
            categoryId: 4,
            name: "Methi Papad",
            description: "Methi Papad 1pcs.",
            price: 10.00,
            count: 0,
            image: "assets/s1/17.jpeg",
          },
          {
            id: 29,
            categoryId: 4,
            name: "Chili Pokoda",
            description: "Chili Pokoda 2 pcs.",
            price: 5.00,
            count: 0,
            image: "assets/s1/18.jpeg",
          },
        ],
      },
      // Store #2
      {
        id: 2,
        name: 'Ang Hair Salon',
        reviewsCount: 3,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s2/banner/Haircut.jpg',
        avatarImage: 'assets/s2/banner/Haircut.jpg',
        logo: 'assets/s2/icon/Capture-HairCutSaloon.PNG',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 0.0,
       image: 'assets/s2/icon/Capture-HairCutSaloon.PNG',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Man haircut 男士理发 Potongan rambut lelaki : RM15-30",
            description: "Make appointment for MAN haircut 预约男士理发 Buat temujanji untuk potongan rambut lelaki",
            price: 30.00,
            count: 0,
            image:
              "assets/s2/ManHaircut.jpg",

          },
          {
            id: 2,
            categoryId: 2,
            name: "Women haircut 女性理发 Potongan rambut wanita : RM20-50",
            description: "Make appointment for WOMEN haircut 预约女士理发 Buat janji untuk potongan rambut wanita",
            price: 50.00,
            count: 0,
            image:
              "assets/s2/WomenHaircut.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Children haircut 儿童理发 Potongan rambut kanak-kanak : RM5-10",
            description: "Make appointment for CHILDREN haircut 预约儿童理发 Buat janji untuk potongan rambut kanak-kanak",
            price: 10.00,
            count: 0,
            image:
              "assets/s2/ChildrenHairCut.jpg",
          },

        ],
      },
      // Store #3
      {
        id: 3,
        name: 'Ah Chong Durian',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s3/banner/AhChongDurianMerchant-BackgroundImage.jpg',
        avatarImage: 'assets/s3/banner/AhChongDurianMerchant-BackgroundImage.jpg',
        logo: 'assets/s3/logo/Logo.jpeg',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 0.00,
        image: 'assets/s3/logo/Logo.jpeg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Kampung Durian",
            description: "Raub old durian tree. All in boxes, 500grams each. All fresh from Pahang. Characteristics: bitter with a little sweet, do not like to eat sweet people do not waste time to ask and order. 都是盒装，每一盒500g. 特征：苦带一点甜，完全不喜欢吃甜的人千万别浪费时间询问和下单了. Raub老树A等.",
            price: 20.00,
            count:0,
            image:
              "assets/s3/AhChongDurian-SKU1.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "D2, D7, D24, D78, D123, Hor Loh ,D144 Durian",
            description: "Raub old durian tree. All in boxes, 500grams each. All fresh from Pahang. Characteristics: bitter with a little sweet, do not like to eat sweet people do not waste time to ask and order. 都是盒装，每一盒500g. 特征：苦带一点甜， 完全不喜欢吃甜的人千万别浪费时间询问和下单了. Raub老树A等.",
            price: 35.00,
            count:0,
            image:
              "assets/s3/AhChongDurian-SKU2.PNG",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Musang King Durian",
            description: "Raub old durian tree. All in boxes, 500grams each. All fresh from Pahang. Characteristics: bitter with a little sweet, do not like to eat sweet people do not waste time to ask and order. 都是盒装，每一盒500g. 特征：苦带一点甜， 完全不喜欢吃甜的人千万别浪费时间询问和下单了. Raub老树A等.",
            price: 80.00,
            count:0,
            image:
              "assets/s3/AhChongDurian-SKU3.PNG",
          },
        ],
      },
      // Store #4
      {
        id: 4,
        name: 'KY Mobile Top Up',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s4/banner/bannerf.jpeg',
        avatarImage: 'assets/s4/banner/bannerf.jpeg',
        logo: 'assets/s4/StoreLogo/Capture-MobileTopUpLogo.png',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 0.00,
        image: 'assets/s4/StoreLogo/Capture-MobileTopUpLogo.png',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Celcom Top Up - 5",
            description: "Top up value for prepaid card -RM5 Celcom",
            price: 5.00,
            count:0,
            image:
              "assets/s4/topup-celcom-RM5.jpg",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Celcom Top Up - 10",
            description: "Top up value for prepaid card - RM10 Celcom",
            price: 10.00,
            count:0,
            image:
            "assets/s4/topup-celcom-RM10.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Celcom Top Up - 30",
            description: "Top up value for prepaid card - RM30 Celcom",
            price: 30.00,
            count:0,
            image:
            "assets/s4/topup-celcom-RM30.jpg",
          },
          {
            id: 4,
            categoryId: 4,
            name: "DiGi Top Up - 5",
            description: "Top up value for prepaid card - RM5 Digi",
            price: 5.00,
            count:0,
            image: "assets/s4/topup-digi-RM5.jpg",
          },
          {
            id: 5,
            categoryId: 1,
            name: "DiGi Top Up - 10",
            description: "Top up value for prepaid card - RM10 Digi",
            price: 10.00,
            count:0,
            image: "assets/s4/topup-digi-RM10.jpg",
          },
          {
            id: 6,
            categoryId: 2,
            name: "DiGi Top Up - 30",
            description: "Top up value for prepaid card - RM30Digi",
            price: 30.00,
            count:0,
            image: "assets/s4/topup-digi-RM30.jpg",
          },
          {
            id: 7,
            categoryId: 3,
            name: "HotLink Top Up - 5",
            description: "Top up value for prepaid card - RM5 HotLink",
            price: 5.00,
            count:0,
            image: "assets/s4/topup-hotlink-RM5.jpg",
          },
          {
            id: 8,
            categoryId: 4,
            name: "HotLink Top Up - 10",
            description: "Top up value for prepaid card - RM10 HotLink",
            price: 10.00,
            count:0,
            image: "assets/s4/topup-hotlink-RM10.jpg",
          },
          {
            id: 9,
            categoryId: 4,
            name: "HotLink Top Up - 30",
            description: "Top up value for prepaid card - RM30 HotLink",
            price: 30.00,
            count:0,
            image: "assets/s4/topup-hotlink-RM30.jpg",
          },
          {
            id: 10,
            categoryId: 4,
            name: "RedOne Top Up - 5",
            description: "Top up value for prepaid card - RM5 RedOne",
            price: 5.00,
            count:0,
            image: "assets/s4/topup-redone-RM5.jpg",
          },
          {
            id: 11,
            categoryId: 4,
            name: "RedOne Top Up - 10",
            description: "Top up value for prepaid card - RM10 RedOne",
            price: 10.00,
            count:0,
            image: "assets/s4/topup-redone-RM10.jpg",
          },
          {
            id: 12,
            categoryId: 4,
            name: "RedOne Top Up - 30",
            description: "Top up value for prepaid card - RM30 RedOne",
            price: 30.00,
            count:0,
            image: "assets/s4/topup-redone-RM30.jpg",
          },
        ]
      },
      // Store #5
      {
        id: 5,
        name: 'Chantique Nasi Lemak',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s5/banner/ChantiqueNasiLemakMerchant-BackgroundImage.jpg',
        avatarImage: 'assets/s5/banner/ChantiqueNasiLemakMerchant-BackgroundImage.jpg',
        logo: 'assets/s5/icon/ch.jpg',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 0.00,
        image: 'assets/s5/icon/ch.jpg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Nasi Lemak Bilis Telur",
            description: "Nasi lemak anchovies & egg",
            price: 6.00,
            count:0,
            image:
              "assets/s5/chantiqueNasiLemak-SKU1.PNG",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Nasi Lemak Ayam Goreng",
            description: "Nasi lemak fried chicken",
            price: 8.50,
            count:0,
            image:
            "assets/s5/chantiqueNasiLemak-SKU2.PNG",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Nasi Lemak Rendang Ayam",
            description: "Nasi lemak chicken rendang",
            price: 9.50,
            count:0,
            image:
            "assets/s5/chantiqueNasiLemak-SKU3.PNG",
          },
          {
            id: 4,
            categoryId: 4,
            name: "Nasi Lemak Paru Balado",
            description: "Nasi lemak chilli beef lungs",
            price: 9.50,
            count:0,
            image: "assets/s5/chantiqueNasiLemak-SKU4.PNG",
          },
          {
            id: 5,
            categoryId: 1,
            name: "Nasi Lemak Kacang Buncis",
            description: "Nasi lemak green beans",
            price: 7.50,
            count:0,
            image: "assets/s5/chantiqueNasiLemak-SKU5.PNG",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Nasi Lemak Rendang Daging",
            description: "Nasi lemak beef rendang",
            price: 9.50,
            count:0,
            image: "assets/s5/chantiqueNasiLemak-SKU6.PNG",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Nasi Lemak Sambal Sotong",
            description: "Nasi lemak spicy cuttlefish",
            price: 9.50,
            count:0,
            image: "assets/s5/chantiqueNasiLemak-SKU7.PNG",
          },
          {
            id: 8,
            categoryId: 4,
            name: "Chef Special - Lontong",
            description: "Coconut soup with vegetable & rice cakes",
            price: 9.50,
            count:0,
            image: "assets/s5/chantiqueNasiLemak-SKU8.PNG",
          },
        ]
      },
      // Store #6
      {
        id: 6,
        name: 'Tanjung Sepat Fishball',
        reviewsCount: 4,
        qualification: 5,
        openingHour: 10,
        backgroundImage: 'assets/s6/banner/TanjungSepatMerchant-BackgroundImage.jpg',
        avatarImage: 'assets/s6/banner/TanjungSepatMerchant-BackgroundImage.jpg',
        logo: 'assets/s6/icon/TanjungSepatSeafoodLogo.jpg',
        icon: '',
        phoneNumber: '60108200805',
        deliveryFee: 0.00,
        image: 'assets/s6/icon/TanjungSepatSeafoodLogo.jpg',
        categories: [
          {
            id: 1,
            title: "Main",
            active: true,
          },
        ],
        plates: [
          {
            id: 1,
            categoryId: 1,
            name: "Fried Fish Ball",
            description: "Fried Fish Ball 15 pcs 炸丸15粒",
            price: 10.00,
            count:0,
            image:
              "assets/s6/TanjunSepatFishBall-SKU1.jpg",
          },
          {
            id: 2,
            categoryId: 2,
            name: "Fish Cake",
            description: "Fish Cake 6 pcs 鱼饼6片",
            price: 10.00,
            count:0,
            image:
            "assets/s6/TanjunSepatFishBall-SKU2.jpg",
          },
          {
            id: 3,
            categoryId: 3,
            name: "Spring Rolls",
            description: "Spring Rolls 9 pcs 春卷9条",
            price: 10.00,
            count:0,
            image:
            "assets/s6/TanjunSepatFishBall-SKU3.jpg",
          },
          {
            id: 4,
            categoryId: 4,
            name: "Small Fried Fu Chuk",
            description: "Small Fried Fu Chuk 20 pcs 小豆支2O片",
            price: 9.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU4.jpg",
          },
          {
            id: 5,
            categoryId: 1,
            name: "Fried Bean curd",
            description: "Fried Bean curd 9 pcs 豆卜9片",
            price: 10.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU5.jpg",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Long Fu Chuk",
            description: "Long Fu Chuk 1 long pcs 长豆支1片",
            price: 9.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU6.jpg",
          },
          {
            id: 7,
            categoryId: 3,
            name: "Spicy Vege Fish Cake",
            description: "Spicy Vege Fish Cake 7 pcs 辣菜饼7片",
            price: 15.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU7.jpg",
          },
          {
            id: 8,
            categoryId: 4,
            name: "Saury Fish Ball",
            description: "Saury Fish Ball Big 20 pcs 西刀大鱼丸20 粒",
            price: 16.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU8.jpg",
          },
          {
            id: 9,
            categoryId: 4,
            name: "Saury Fish Ball",
            description: " Saury Fish BallSmall 50 pcs 西刀小鱼丸50粒",
            price: 15.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU9.jpg",
          },
          {
            id: 10,
            categoryId: 4,
            name: "Fuk Chuk Roll",
            description: "Fuk Chuk Roll 6 pcs 豆支卷 6片 ",
            price: 9.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU10.jpg",
          },
          {
            id: 11,
            categoryId: 4,
            name: "Vege Fish Ball",
            description: "Vege Fish Ball 菜丸 ",
            price: 12.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU11.jpg",
          },
          {
            id: 12,
            categoryId: 4,
            name: "Fish Noodles",
            description: "Fish Noodles 鱼面 ",
            price: 12.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU12.jpg",
          },
          {
            id: 13,
            categoryId: 4,
            name: "Fu Zhou Fish Ball",
            description: "Fu Zhou Fish Ball 福州鱼丸 ",
            price: 12.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU13.jpg",
          },
          {
            id: 14,
            categoryId: 4,
            name: "Flower Fish Ball",
            description: "Flower Fish Ball 鱼花 ",
            price: 12.00,
            count:0,
            image: "assets/s6/TanjunSepatFishBall-SKU14.jpg",
          },
        ]
      }
    ];
  }
}
